apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-board-fe
spec:
  replicas: 3
  selector:
    matchLabels:
      app: board-fe
  template:
    metadata:
      labels:
        app: board-fe
    spec:
      containers:
        - name: board-fe
          image: kangjoshi/board-fe
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: service-board-fe
spec:
  type: NodePort
  selector:
    app: board-fe
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30006
