apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-board-be
spec:
  replicas: 3
  selector:
    matchLabels:
      app: board-be
  template:
    metadata:
      labels:
        app: board-be
    spec:
      containers:
        - name: board-be
          image: kangjoshi/board-be
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: board-be-config
                  key: profile
          readinessProbe:
            httpGet:
              port: 8080
              path: /monitors
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 60

---
apiVersion: v1
kind: Service
metadata:
  name: service-board-be
spec:
  type: ClusterIP
  selector:
    app: board-be
  ports:
    - port: 80
      targetPort: 8080

