apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-board-fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: board-fe
  template:
    metadata:
      labels:
        app: board-fe
    spec:
      containers:
        - name: board-fe
          image: kangjoshi/board-fe
          imagePullPolicy: IfNotPresent
          readinessProbe:
            httpGet:
              port: 3000
              path: /
            periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: service-board-fe
spec:
  type: ClusterIP
  selector:
    app: board-fe
  ports:
    - port: 80
      targetPort: 3000