apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-{{ .Chart.Name }}-fe
spec:
  replicas: {{ .Values.fe.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-fe
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-fe
    spec:
      containers:
        - name: {{ .Chart.Name }}-fe
          image: "{{ .Values.fe.image.repository }}:{{ .Values.fe.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.fe.image.pullPolicy }}
          readinessProbe:
            {{- toYaml .Values.fe.readinessProbe | nindent 12 }}


---
apiVersion: v1
kind: Service
metadata:
  name: service-{{ .Chart.Name }}-fe
spec:
  type: {{ .Values.fe.service.type }}
  selector:
    app: {{ .Chart.Name }}-fe
  ports:
    - port: {{ .Values.fe.service.port }}
      targetPort: {{ .Values.fe.application.port }}